### ISSUE TITLE
Compilation failed for examples.

### ISSUE THREAD

**Issue by cobordism** [reanimate/reanimate#100]
For some of the examples the output is:

```
Compilation failed

    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
12 | import           Data.String.Here
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by Lemmih** [comment]
Some of the examples depend on the package 'here'. If you use stack, it should be installed automatically. How are you compiling the examples?

**Comment by cobordism** [comment]
I used stack.
`stack path/to/example.hs`

**Comment by cobordism** [comment]
So it works now after having manually run `stack install here`.
So I guess the issue is figuring out why it was not automatic.

**Comment by Lemmih** [comment]
Ah, I had forgotten to add '--package here' to some of the examples that use the 'here' package. Should be fixed now.

**Comment by Lemmih** [comment]
I've completely moved away from the 'here' package in favour of 'neat-interpolation'. This simplifies things and the examples no longer have any extra dependencies.
