### ISSUE TITLE
Trouble with morphology examples

### ISSUE THREAD

**Issue by cobordism** [reanimate/reanimate#103]
If you open the example file morphology_linear.hs and replace `stages` with something like
```
    stages = map (lowerTransformations . scale 0.8 . pathify . center) $ colorize
      [ latex  "$e^{i\\pi}+1=0$",
        latex "hello W$\\xrightarrow{\\text{orl}}d$"
      ]
```
it will not compile.  It stays stuck on "Frames generated: 0/480"

Am I doing something wrong?

**Comment by Lemmih** [comment]
You're not doing anything wrong. The morphing code is just very immature. I've pushed a patch that reverts to a morphing algorithm that should always work.

The morphing framework will eventually support a slew of different algorithms but right now it's pretty much just a mess.

**Comment by cobordism** [comment]
Ok. Thanks for the response.
I'd been working on making animations with manim and I used to joke "I just wish it were not written in python but something like idris instead". I'd always wanted to learn more idris (or haskell) and that way I could do two things at once. So I was very excited to find reanimate a few days ago. Alas, it seems the code-base is not quite mature enough yet for my needs.

If it's all right with you I'll continue to play with the code and post any issues I encounter. Let me know if it gets irritating, and I'll stop.

**Comment by Lemmih** [comment]
Not irritating at all; You're doing me a huge service.

Do you know which features you need from manim? Morphing and fonts are high on my TODO list and should be ready in a couple of weeks. Would that be enough to make reanimate useful for you?

**Comment by cobordism** [comment]
cool.
Yes. Morphing LaTeX is the most important ingredient for me.

Does reanimate have a discord, or a mattermost, or a subreddit, or some place to discuss things that don't quite rise to the level of github issues?

**Comment by Lemmih** [comment]
There is a gitter chatroom: https://gitter.im/reanimate/community
