### ISSUE TITLE
Transparency seems ignored with RasterRSvg

### ISSUE THREAD

**Issue by Krantz-XRF** [reanimate/reanimate#109]
I installed `ffmpeg` using the bundled `MSYS2` from `stack`, and it is not compiled with `--enable-librsvg`, so I installed `rsvg` separately. Today I realized that in the generated video, all transparency-related effects are gone. It appears as if the alpha channel were simply dropped:

- Providing a semi-transparent `PixelRGBA8` (with e.g. alpha=0.5) produces exactly the same result as alpha=1;
- `fadeInE`/`fadeOutE` has no effect;

I suspect that it is due to `RasterRSvg`, so I tried with `ImageMagick`, and surprisingly I get a completely white video. I really don't have much experience on `ffmpeg`, `rsvg`, etc., so I have no idea what's going on.

I'll try run my program on `WSL` (`Arch Linux` and `Ubuntu`), and `MacOS`, for I guess this weird behaviour only happens on Windows. I'll post my result here, so that someone might be able to spot the actual problem. FYI, my code can be found in [my GitHub repo](https://github.com/Krantz-XRF/reanimate-projects).

**Comment by Lemmih** [comment]
Running the code from your repository, I get identical results when comparing rsvg and ffmpeg under Linux:

ffmpeg:
![ffmpeg](https://user-images.githubusercontent.com/1443107/87399969-c10b8c00-c5ea-11ea-8a34-a90cb4caae4e.gif)

rsvg:
![rsvg](https://user-images.githubusercontent.com/1443107/87399986-c5d04000-c5ea-11ea-9ff7-82473453000d.gif)

Curious to know if things work differently under Windows. Feel free to upload gifs that show unusual or unexpected behaviour.

**Comment by Krantz-XRF** [comment]
Sorry, I must have messed up with my code; now I cannot reproduce the blank `mp4` video from `ImageMagick`, I guess that was an accident.

I tried again with `RSvg` and `ImageMagick`, and I found out `ImageMagick` produced (no matter `mp4` or `gif`) video with white background, while `RSvg` produced video with transparent (`gif`) and black (`mp4`) background. I don't know whether this is the expected behaviour. (See the screenshot below.)

![image](https://user-images.githubusercontent.com/17098235/87404917-5c9ffb00-c5f1-11ea-8249-703ccf4b9ecd.png)

Also, I should have added `fadeOutE` in [line 43 of `Motion.hs`](https://github.com/Krantz-XRF/reanimate-projects/blob/master/2048IsHard/src/A2048/Motion.hs#L43), but I don't see a fade out effect on the first two lines of 2, 0, 4, and 8 (I expect them to fade out while moving upward). I might have used `fadeOutE` incorrectly.

The transparency issue, as is mentioned above, still happens. Modify [line 51 of Config.hs]() to use colour `eee4da59` instead of `cdc0b4` (which is the mixed colour of `#eee4da59` and background `bbada0`), I see the following difference (with RasterRSvg):

| Transparency Seems Ignored: `eee4da59` | Manually Mixed Colour: `cdc0b4` |
|-|-|
| ![test](https://user-images.githubusercontent.com/17098235/87406085-d71d4a80-c5f2-11ea-9c51-41bc6197cd58.gif) | ![test](https://user-images.githubusercontent.com/17098235/87406281-18155f00-c5f3-11ea-91e5-0a8ef9249bc1.gif) |

To conclude:

- `fadeOutE` does not make the first two lines (moving upward) fade out (I might have used it incorrectly);
- Transparency in colours does not appear as expected (alpha seems ignored).

**Comment by Lemmih** [comment]
This doesn't look quite right:
> animate $ if fade then fadeOutE dt 0 . f else f

The second controls the level of fade so setting it to '0' means it will never fade. Usually you shouldn't call effects directly but rather use `applyE` or `spriteE`.

Try something like:
> applyE (if fade then fadeOutE else constE id) $ animate f

We can chat on discord if you want more immediate feedback: https://discord.gg/Qs28Dv6

**Comment by Krantz-XRF** [comment]
Solved.
