### ISSUE TITLE
In-browser viewer stuck on ‘Compiling…’ step

### ISSUE THREAD

**Issue by patrickt** [reanimate/reanimate#124]
Hi there 👋 Congratulations on a really, really cool project—I’m very excited to see where it goes.

I’ve been checking `reanimate` out today, and ran into a problem: when running the `drawCircle` example, the viewer app stays in `Compiling…` mode, and does not finish even given considerable time. The listener itself gives standard messages, and emits `Reloading code…` on a file change. Note that mp4 and gif output work perfectly.

I made an effort at debugging this: the WebSocket connection is established properly, but once that happens no further render or layout effects occur.

Running `check`  gives me:
```
reanimate checks:
  Has ffmpeg:                        4.3.1
  Has ffmpeg(rsvg):                  no
  Has dvisvgm:                       'dvisvgm' not found
  Has povray:                        'povray' not found
  Has blender:                       no
  Has rsvg-convert:                  2.48.8
  Has inkscape:                      no
  Has imagemagick:                   7.0.10-25
  Has LaTeX:                         'latex' not found
  Has LaTeX package 'babel':         n/a
  Has LaTeX package 'preview':       n/a
  Has LaTeX package 'amsmath':       n/a
  Has XeLaTeX:                       'xelatex' not found
  Has XeLaTeX package 'ctex':        n/a
```

I’m using macOS Catalina 10.15.6, with Safari 13.1.2, running from fish-shell. Thanks in advance, and please forgive me if the solution is obvious!

**Comment by Lemmih** [comment]
Hi Patrick

How are you running the drawCircle example? Are you using stack?

This is what it looks like for me when I use Safari:
[Imgur](https://imgur.com/sBEV4Gk)

**Comment by patrickt** [comment]
I’m using cabal-install v3.2.0.0. I’ll give stack a shot.

**Comment by Lemmih** [comment]
The browser-viewer uses stack under the hood to compile the animation. Stack probably tried to install a version of GHC + all of reanimate's dependencies. That's why it was stuck on "Compiling...".

I wonder if I can detect whether cabal or stack is being used.
