### ISSUE TITLE
reanimate-svg is slow

### ISSUE THREAD

**Issue by Lemmih** [reanimate/reanimate#127]
- [ ] Don't force paths to be decoded. Something like `Either [PathCommand] Text` would be better. And perhaps use vectors instead of lists.
 - [ ] Don't convert to XML before serializing.
 - [ ] Don't serialize to `String`. Use `blaze-svg` to serialize directly to `Text` or directly to a file.
 - [ ] Don't use `String` internally, use `Text` instead. For inlined images, this makes a big difference.
 - [ ] Speculative: Compress SVG tree by using `{-# UNPACK #-}`?

**Comment by joseedil** [comment]
I copied this to reanimate-svg issue tracker.

**Comment by Lemmih** [comment]
Great, thanks!
