### ISSUE TITLE
Problem running examples in nix-shell

### ISSUE THREAD

**Issue by commandodev** [reanimate/reanimate#140]
I'd like to add nix support but I'm having trouble running the examples from a nix-shell:

```
Listening...
Opening browser...
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"

(brave:30564): Gtk-WARNING **: 12:20:35.899: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(brave:30564): Gtk-WARNING **: 12:20:35.899: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(brave:30564): Gtk-WARNING **: 12:20:35.899: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Browser opened.
[30596:30596:0100/000000.000265:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[30596:30596:0100/000000.000669:ERROR:broker_posix.cc(43)] Invalid node channel message
New connection received.
Reloading code...
[30603:30603:0825/122036.043326:ERROR:broker_posix.cc(43)] Invalid node channel message
```

Not sure what I might be missing here!

I'm also getting `Failed to find own source code.` fairly often, which I assume has something to do with stack being called to compile the example?

I tried to change one of the examples to use cabal like so:

```
#!/usr/bin/env cabal
{- cabal:
build-depends: base
            , reanimate
            , reanimate-svg
            , JuicyPixels
-}
```

Which allows me to run the code at least. Is there anything else I could share to aid with debugging? I'm also happy to dog in myself with some pointers :-)

**Comment by Lemmih** [comment]
Does it work if you specify the path to GHC:
```
runhaskell examples/doc_drawCircle.hs --ghc-opt `which ghc`
```

**Comment by Lemmih** [comment]
Oh, and the error messages you pasted are coming from brave, not reanimate. The messages from reanimate look to be alright. The code is running, it received a connection from the browser and it's replying with the SVG frames. Are you seeing any error messages in the browser window?

**Comment by commandodev** [comment]
The browser window just says compilation failed. I'm rebuilding my shell to add texlive at the moment (which may take some time). I'll try with a simpler example after that and report back. Thanks for the swift response :-)

**Comment by commandodev** [comment]
Update:

I tried the runhaskell command and it still doesn't work. Complains about not being able to find reanimate.

I've got the rendering working by changing the `#!` and comment as described.

I still can't get the browser view to work at all. I've tried brave (as opened by the command line) and firefox pointing to the same file. I've got some nixish looking error that I need to look into:

```
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open i915 (search paths /run/opengl-driver/lib/dri)
failed to load driver: i915
MESA-LOADER: failed to open kms_swrast (search paths /run/opengl-driver/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /run/opengl-driver/lib/dri)
failed to load swrast driver
```

But not sure if that could be causing the problem. All I see in the browser is "Compiling..." followed by "Compilation failed" after a short wait.

**Comment by Lemmih** [comment]
Are you using stack or cabal to build reanimate?

If runhaskell doesn't work, you can use GHC directly:
```
ghc examples/doc_drawCircle.hs
./examples/doc_drawCircle --ghc-opt ghc
```

If everything fails, you can render animations to video files and view them with mpv or another player. The browser viewer is there for convenience rather than necessity.

If you want to chat, feel free to join our discord server. https://discord.gg/Qs28Dv6 I'm quite keen on making reanimate easier to use with nix.

**Comment by commandodev** [comment]
Latest upate, after updating the fork of master:

```
[nix-shell:~/docs/1.Projects/VisualiseValue/reanimate]$ ./examples/doc_drawCircle.hs
Warning: The package list for 'hackage.haskell.org' is 122 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (exe:script) (configuration changed)
Configuring executable 'script' for fake-package-0..
Preprocessing executable 'script' for fake-package-0..
Building executable 'script' for fake-package-0..
[1 of 1] Compiling Main             ( Main.hs, /home/ben/docs/1.Projects/VisualiseValue/reanimate/dist-newstyle/build/x86_64-linux/ghc-8.8.3/fake-package-0/x/script/build/script/script-tmp/Main.o )
Linking /home/ben/docs/1.Projects/VisualiseValue/reanimate/dist-newstyle/build/x86_64-linux/ghc-8.8.3/fake-package-0/x/script/build/script/script ...
Rendering in browser window is only available when interpreting.
To render a video file, use the 'render' command or run again with --help
to see all available options.
```

**Comment by Lemmih** [comment]
Can I close this?
