### ISSUE TITLE
Function Plotting

### ISSUE THREAD

**Issue by pdcxs** [reanimate/reanimate#146]
Is there an easy way for function plotting? Such as the ParametricFunction and NumberLine classes in manim.

**Comment by Lemmih** [comment]
Not yet but PRs are very welcome. Classes in manim map roughly to objects in reanimate.

**Comment by pdcxs** [comment]
Thanks a lot for your reply. I suggest that function plotting should be added as an example, because it's a critical part for math animations.

**Comment by Lemmih** [comment]
I completely agree and look forward to your PR. :)

**Comment by pdcxs** [comment]
I'm a beginner in Haskell language, I'll try my best.
