### ISSUE TITLE
Windows SubSystem for Linux fails

### ISSUE THREAD

**Issue by msaroufim** [reanimate/reanimate#185]
Just saw your library mentioned in Hacker News and it's something I've been looking for a while now. I'm not a Haskell or WSL expert so hoping someone can help me out.

Repro instructions in WSL

`sudo apt-get install haskell-stack`

`stack upgrade`

`cd reanimate`

`stack build`

Up until this point everything works fine

Then it fails here

```
stack ./examples/doc_drawCircle.hs
stack: WARNING! Expecting "stack" at line 2, column 4
stack: WARNING! Missing or unusable stack options specification
stack: WARNING! Using runghc without any additional stack options
2020-10-29 17:16:55.48: Listening...
2020-10-29 17:16:57.48: Opening browser...
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "/mnt/c/Users/Mark/Dev/reanimate/.stack-work/install/x86_64-lin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

2020-10-29 17:16:59.44: Browser opened.

```

**Comment by Lemmih** [comment]
Hi @msaroufim. By default reanimate tries to use a browser window to preview your animation. I don't have any experience with WSL but I'm guessing it is not possible to run firefox or chrome from there.

You can either render directly to a video file (`stack ./examples/doc_drawCircle.hs render`) or you can use reanimate directly from Windows.
