### ISSUE TITLE
reanimateLiveEntry only shows animation with given name once, then switches to "main" animation

### ISSUE THREAD

**Issue by jhrcek** [reanimate/reanimate#195]
First I must say that I absolutely love the new live reload. It's very fast and reliable.
I just run into some hiccups with the `reanimateLiveEntry`.

I have a main function which calls `reanimate someAnimation`.
I'd like to work on separate animation, let's call it `other :: Animation`
in `stack ghci` I execute
`:cmd reanimateLiveEntry "other"`
and the `other` animation is correctly rendered in viewer.

The problem is that after I make changes to the file and save it (and on any other subsequent changes), the animation in main is rendered in the viewer instead of the "other" animation.

Here's some code to illustrate this

```haskell
module Main where

import Reanimate

main :: IO ()
main = reanimate square

square :: Animation
square = animate . const $ mkRect 1 1

circle :: Animation
circle = animate . const $ mkCircle 1
```

And a gif illustrating this behavior.
![reanimateLiveEntry](https://user-images.githubusercontent.com/2716069/107365032-887a5500-6adc-11eb-8725-2bfcaf1a9016.gif)

**Comment by Lemmih** [comment]
Oh, right, oops. `reanimateLiveEntry` should of course call itself instead of `reanimateLive`.

**Comment by jhrcek** [comment]
I thought it would be something simple :smile:

**Comment by Lemmih** [comment]
Fix pushed to master.

**Comment by jhrcek** [comment]
Thanks for the quick fix. I tested it and it works well :+1:
