### ISSUE TITLE
"Color" values that are a string should probably allow things like hex values.

### ISSUE THREAD

**Issue by seanparsons** [reanimate/reanimate#196]
The comment attached to `withFillColor` indicates it takes the `fill` SVG attribute type which would include things like `#112233`:
[https://hackage.haskell.org/package/reanimate-1.1.3.2/docs/src/Reanimate.Svg.Constructors.html#withFillColor](https://hackage.haskell.org/package/reanimate-1.1.3.2/docs/src/Reanimate.Svg.Constructors.html#withFillColor)

But internally it's delegating that `String` value to `mkColor` which does a lookup on colour names and otherwise defaults it to a near white value:
[https://hackage.haskell.org/package/reanimate-1.1.3.2/docs/src/Reanimate.Svg.Constructors.html#mkColor](https://hackage.haskell.org/package/reanimate-1.1.3.2/docs/src/Reanimate.Svg.Constructors.html#mkColor)

I think either the comment needs fixing to guide people onto using other calls or it should passthrough value fill values.

**Comment by Lemmih** [comment]
Yeah, this is a known bug in `reanimate-svg`.
