### ISSUE TITLE
How do I use a non-default browser

### ISSUE THREAD

**Issue by tomjaguarpaw** [reanimate/reanimate#203]
I'd like Reanimate to load the animation in a browser that is not my default one. Is that possible? It seems not given

https://github.com/reanimate/reanimate/blob/5ea023980ff7f488934d40593cc5069f5fd038b0/src/Reanimate/Driver/Server.hs#L126

Forcing users to use the default browser only seems unfortunately inflexible!

**Comment by Lemmih** [comment]
You can always just open your favorite browser manually and copy over the URL. Since this only has to be done once per session, I don't think it merits a configuration option.

**Comment by tomjaguarpaw** [comment]
Hi @Lemmih, thanks for your response.

> You can always just open your favorite browser manually and copy over the URL

That would be great! But where do I get the URL from? My system is set to load the Calibre eBook reader as the default browser (I have no idea why). It doesn't show the URL so there's no way for me to copy it across. Is it possible to get reanimate to print the URL on stdout?

(I realise that my setup is rather weird. If my aim were just to use reanimate in a browser then I'd set a better default browser. However, I think this experience highlights a way that reanimate could be slightly more flexible.)

Feel free to close this issue if you prefer. It's not a big deal for me.

**Comment by Lemmih** [comment]
I don't think it's worthwhile supporting this use-case. You can solve the problem by changing your default browser to Firefox or chrome, and then bookmarking the URL.
