### ISSUE TITLE
Wrong default latex svg behavior

### ISSUE THREAD

**Issue by pdcxs** [reanimate/reanimate#208]
I try to use reanimate on windows, with latex version: `MiKTeX-pdfTeX 2.9.7439 (1.40.21) (MiKTeX 2.9.7440 64-bit)` and latest reanimate with resolver lts-18.0, when I compile following program:
``` haskell
{-# LANGUAGE OverloadedStrings #-}
module Main(main) where

import Reanimate
import Reanimate.Builtin.Documentation
import Graphics.SvgTree

env :: Animation -> Animation 
env = addStatic bg

bg :: SVG
bg = mkBackground "lightblue"

animation :: Animation
animation = env $ scene $ do
    newSpriteSVG_ equation
    wait 1

equation :: SVG 
equation =
    scale 3 $ center $
    latexAlign "E = mc^2"

main :: IO ()
main = reanimate $ docEnv animation
```
It generates too bold texts. I found that it uses lines to draw the contour of the latex svg, If I change the codes as follows:
```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main(main) where

import Reanimate
import Reanimate.Builtin.Documentation
import Graphics.SvgTree

env :: Animation -> Animation 
env = addStatic bg

bg :: SVG
bg = mkBackground "lightblue"

animation :: Animation
animation = env $ scene $ do
    newSpriteSVG_ equation
    wait 1

equation :: SVG 
equation =
    withFillOpacity 1.0 $
    withFillColor "black" $
    withStrokeWidth 0 $
    scale 3 $ center $
    latexAlign "E = mc^2"

main :: IO ()
main = reanimate $ docEnv animation
```
It becomes normal. Is there a way to fix the default svg draw method for latex? Configure like this at each time is too verbose, I think.

**Comment by Lemmih** [comment]
You can define your own `latex` function which sets the stroke width to zero. Or you could set the stroke width to zero as default for your entire animation.

**Comment by pdcxs** [comment]
> You can define your own `latex` function which sets the stroke width to zero. Or you could set the stroke width to zero as default for your entire animation.

Thanks for your reply. I know how to write correct animations. I just wonder if the default behaviour of the latex function should be modified in the reanimate library.

**Comment by Lemmih** [comment]
I don't think it should. `latex` just gives you the path for a given expression. How you draw it is up to you. There might be room for a separate function that sets the stroke-width and fill attributes but I don't think it would be that useful.

**Comment by pdcxs** [comment]
> I don't think it should. `latex` just gives you the path for a given expression. How you draw it is up to you. There might be room for a separate function that sets the stroke-width and fill attributes but I don't think it would be that useful.

OK, thanks a lot.
