### ISSUE TITLE
Feature Request: rendering without optparse

### ISSUE THREAD

**Issue by s-zeng** [reanimate/reanimate#211]
We have an application (wherein we have our own command line arguments), and would like to use reanimate to render some animations. However, I have not been able to find a way to tell reanimate to render an animation and pass in options without it highjacking our own options parser. Furthermore, there seems to be some frail self-code-checking logic, since we often encounter "Failed to find own source code" when trying to run a branch of our codebase that runs `reanimate`.

Is there any way to render files without having to make the entire executable be solely for the purpose of the animation?

**Comment by Lemmih** [comment]
You can use [withArgs](https://hackage.haskell.org/package/base-4.15.0.0/docs/System-Environment.html#v:withArgs) to set the rendering arguments. You might want something like: `withArgs ["render", "--target", "your_animation.mp4"] reanimate`.

**Comment by s-zeng** [comment]
Thanks for the response and help on discord!
