### ISSUE TITLE
Different animations in browser and rendered when using scaleXY

### ISSUE THREAD

**Issue by twenty5151** [reanimate/reanimate#213]
The code to reproduce:

```hs
{-# LANGUAGE OverloadedStrings #-}

module Main(main) where

import Reanimate

f t = if t < 0.8
       then 1 - t
       else 0

test t = mkGroup [ scaleXY 1 (f t) $ mkText "test"
                 ]

main :: IO ()
main = reanimate $ addStatic (mkBackground "white") $ mkAnimation 2 test
```

`scale (f t)` works for both cases. `scaleToSize  1 (f t)`, `scaleToWidth (f t)`, and `scaleToHeight (f t)` all result in a static text in browser view, but simply a blank render on file. (Re #63, the file size of the blank video is not zero). Regardless of which animations are correct, the video in the browser and rendered into a file should be consistent.

Steps to reproduce:
1. `stack new debug github:reanimate/plain`
2. paste in the above code snippet to `Main.hs`
3. `stack build && stack install`
4. `debug view` (And get the following video, which should be the correct one)

https://user-images.githubusercontent.com/44771158/128633606-2283452b-55fe-4184-ae54-2f7723d6958b.mp4

- `debug render` (And get the following video)

https://user-images.githubusercontent.com/44771158/128633160-97e89357-7cb6-46f3-be9a-e7d9bbc2b43b.mp4

Output of `debug check`

```
reanimate checks:
  Has ffmpeg:                        too old:  < 4.1.3
  Has ffmpeg(rsvg):                  yes
  Has dvisvgm:                       /usr/bin/dvisvgm
  Has povray:                        'povray' not found
  Has blender:                       no
  Has rsvg-convert:                  2.50.7
  Has inkscape:                      1.1
  Has imagemagick:                   7.1.0-4
  Has LaTeX:                         /usr/bin/latex
  Has LaTeX package 'babel':         missing
  Has LaTeX package 'preview':       missing
  Has LaTeX package 'amsmath':       missing
  Has XeLaTeX:                       /usr/bin/xelatex
  Has XeLaTeX package 'ctex':        missing
```

Which is strange because my ffmpeg is updated. Perhaps the 'n' is the cause? Output of `ffmpeg -version`:
```
ffmpeg version n4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11.1.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

**Comment by Lemmih** [comment]
SVG text is rendered differently by each of the backends. If you want consistent text then you have to do the font handling yourself or use `latex`.

SVG text also doesn't have a defined width or height because those properties depend on the font which is handled entirely by the rasteriser. This means the `scaleToSize/scaleToWidth/scaleToHeight` functions won't do what you expect. With the width and height being undefined, there's literally no way to get the expected behaviour, unfortunately.

**Comment by twenty5151** [comment]
Oh, I used `mkText` because the `latex` function uses `pdflatex` by default and crashes with `! LaTeX Error: File `standalone.cls' not found..` I think this isn't correct? Is there any way to switch to the "correct" latex?

**Comment by Lemmih** [comment]
It defaults to `latex` (which might be `pdflatex` on your machine) but you can also use `xelatex` and `lualatex`.

Here's the documentation: https://hackage.haskell.org/package/reanimate-1.1.4.0/docs/Reanimate-LaTeX.html

**Comment by twenty5151** [comment]
I installed amsmath (from `texlive-latexextra`) and pdf2svg and it works now. Thanks!
