### ISSUE TITLE
More graphs?

### ISSUE THREAD

**Issue by cdupont** [reanimate/reanimate#230]
Hello,
I like a lot reanimate. I think what is mostly missing at the moment is capacities on graphs...
How to plot and animate a graph? Do you have any plan to add this?
Also, additional capacities on graphics would be nice. For instance, when I tried I didn't find arrows to point at stuff.
Thanks
P.S. I posted on reddit if you didn't saw it: https://www.reddit.com/r/haskell/comments/q3szzj/reanimate_great_library_for_creating_math_videos/

**Comment by Lemmih** [comment]
Reanimate can animate any SVG image but it is up to you to actually generate the SVG. It is unlikely to ever have built-in support for arrows, graphs, etc. Perhaps use chart-svg: https://hackage.haskell.org/package/chart-svg

**Comment by mpilgrem** [comment]
I've put the underlying code for the animated graph above at https://github.com/mpilgrem/reanimate-graph

**Comment by Lemmih** [comment]
This seems resolved.
