### ISSUE TITLE
Animate from SVG files

### ISSUE THREAD

**Issue by cdupont** [reanimate/reanimate#243]
Hello,
I have an SVG file, that I would like to animate:
![image](https://user-images.githubusercontent.com/484033/141674794-fc5b5cc2-6ccc-4967-ab38-4a628c15e5e8.png)

I read the file with:
```
anim :: IO ()
anim = do
  doc <- loadSvgFile "test.svg" 
  tree <- case doc of
    Nothing  -> error "Malformed svg"
    Just svg -> return $ embedDocument svg
  reanimate $ addStatic (mkBackground "cyan") $ staticFrame 1 $ tree
```
This works well.
However, I'm not sure where to go from here.
I would like e.g. make the arrows appear little by little.
How to do that?

Thanks a lot

**Comment by Lemmih** [comment]
Closing as this is not a reanimate issue. Feel free to raise this question in the "Discussions" tab.

**Comment by cdupont** [comment]
Sorry I didn't know there was a discussion tab. I moved it: https://github.com/reanimate/reanimate/discussions/245
