### ISSUE TITLE
boundingBox returns (0,0,0,0) for Trees generated with mkText

### ISSUE THREAD

**Issue by expipiplus1** [reanimate/reanimate#94]

**Comment by Lemmih** [comment]
Yeah, the bounding box of text depends on the font. There's not much to do here except make a note of it in the documentation.

**Comment by expipiplus1** [comment]
I guess there are quite a few subtleties with this function, such as line
width not being taken into account etc..

**Comment by Lemmih** [comment]
Computing correct bounding boxes for all of SVG, including masks and filter effects, would be a mighty burden. If you need accurate bounding boxes, you can always raster the SVG fragment and look at the pixels. There are nice helper functions for this.

**Comment by Lemmih** [comment]
I've updated the docs to say that bounding boxes are best-effort.

**Comment by expipiplus1** [comment]
Thank!
